language: java
sudo: required
jdk:
- openjdk8
before_install:
 - openssl aes-256-cbc -K $encrypted_b2959122ad0e_key -iv $encrypted_b2959122ad0e_iv
  -in travis_deploy-key.enc -out travis_deploy-key -d
 - chmod +x mvnw
cache:
  directories:
  - "$HOME/.cache"
install:
- true
addons:
  apt:
    update: true
jobs:
  include:
  - stage: unit tests & coverage
    script:
    - "./mvnw clean install"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy to prod
    deploy:
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: $HEROKU_TOKEN
      app: powerchecker
